<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Content Update="dungeon-rewards.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Assets\Scripts\ThirdParty\kcp2k\*.cs" Link="ThirdParty\kcp2k\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
